-- AlterTable
ALTER TABLE `booking_events` MODIFY `type` ENUM('CREATED', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'ROOM_CHANGED', 'EXTENDED', 'CANCELLED', 'AUTO_CANCELLED', 'REJECTED', 'EXPIRED', 'ADAPTER_SYNC_REQUESTED', 'NOTIFICATION_QUEUED') NOT NULL,
    MODIFY `from_status` ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CANCELLED', 'COMPLETED', 'EXPIRED', 'AUTO_CANCELLED', 'REJECTED') NULL,
    MODIFY `to_status` ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CANCELLED', 'COMPLETED', 'EXPIRED', 'AUTO_CANCELLED', 'REJECTED') NULL;

-- AlterTable
ALTER TABLE `bookings` ADD COLUMN `checked_in_at` DATETIME(3) NULL,
    ADD COLUMN `checked_out_at` DATETIME(3) NULL,
    ADD COLUMN `early_checkin_charge` DECIMAL(10, 2) NULL,
    ADD COLUMN `early_checkin_type` ENUM('NONE', 'FULL', 'MANUAL') NOT NULL DEFAULT 'NONE',
    ADD COLUMN `late_checkout_charge` DECIMAL(10, 2) NULL,
    ADD COLUMN `late_checkout_type` ENUM('NONE', 'FULL', 'MANUAL') NOT NULL DEFAULT 'NONE',
    MODIFY `booking_status` ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CANCELLED', 'COMPLETED', 'EXPIRED', 'AUTO_CANCELLED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
